
trigger:
- main

pool:
  vmImage: ubuntu-latest


jobs:
- job: Build_and_Push
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '11'
      addToPath: true

  - script: |
      ./mvnw clean install
    displayName: 'Build Spring Boot App'

  - task: Docker@2
    displayName: 'Build Docker Image for Spring Boot'
    inputs:
      command: 'build'
      Dockerfile: '$(Build.SourcesDirectory)/dockerfileboot'

  - task: Docker@2
    displayName: 'Build Docker Image for ReactJs App'
    inputs:
      command: 'build'
      Dockerfile: '$(Build.SourcesDirectory)/src/main/webapp/reactjs/dockerfilejs'
      includeLatestTag: true
      

