# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: pipeline
  
jobs:
- job: BuildBackend
  displayName: 'Build Backend'
  steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '11'
      addToPath: true
  - script: |
      ./mvnw clean install
    displayName: 'Build Backend'

- job: BuildFrontend
  displayName: 'Build Frontend'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14'
      addToPath: true
  - script: |
      cd ./src/main/webapp/reactjs
      npm install
      npm run build
    displayName: 'Build Frontend'
  
