
trigger:
  branches:
    include:
      - main

pool:
  name: 'DESKTOP-BRLBMDI'

jobs:
- job: Build_and_Push
  pool:
    name: 'DESKTOP-BRLBMDI'  
  strategy:
    maxParallel: 1
  steps:
  - script: |
      ./mvnw clean install
    displayName: 'Build Spring Boot App'

  - task: Docker@2
    displayName: 'Build Docker Image for Spring Boot'
    inputs:
      command: 'build'
      Dockerfile: '$(Build.SourcesDirectory)/dockerfileboot'

  - task: Docker@2
    displayName: 'Build Docker Image for ReactJs App'
    inputs:
      command: 'build'
      Dockerfile: '$(Build.SourcesDirectory)/src/main/webapp/reactjs/dockerfilejs'
      includeLatestTag: true
