version: '3'
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8081:8081
    env_file:
      - .env
    networks:
      - springbackenddata-net
  frontend:
    container_name: frontend
    build:
      context: ./src/main/webapp/reactjs
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - springbackenddata-net
  database:
    image: postgres
    restart: always
    container_name: database
    ports:
      - 5432:5432
    env_file:
      - .env 
    networks:
      - springbackenddata-net
networks:
  springbackenddata-net:
