version: '3'

services:
  backend:
    image: backend
    container_name: backend 
    ports:
      - "8081:8081"

    env_file:
      - .env

    depends_on:
      - postgres

  frontend:
    image: frontend 
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  postgres:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
 
